import pytest
import json
from pathlib import Path
import re

def test_phase4_report_schema():
    db_path = Path("outputs/database.jsonl")
    assert db_path.exists(), "Database log should be autonomously generated"
    
    records = []
    with open(db_path, "r", encoding="utf-8") as f:
        for line in f:
            records.append(json.loads(line))
            
    assert len(records) > 0, "Database should contain routed events"
    
    record = records[0]
    
    # Verify strict UUID and ISO formats autonomously generated by the router
    assert "event_id" in record
    assert "timestamp" in record
    assert "clip_id" in record
    assert "zone" in record
    assert "behavior_class" in record
    assert "policy_rule_ref" in record
    assert "event_description" in record
    assert "severity" in record
    assert "escalation_action" in record
    
    # Validate UUID format
    assert len(record["event_id"]) == 36, "event_id must be a UUID"
    
    # Validate ISO 8601 format (e.g. 2026-06-17T03:16:13Z)
    assert re.match(r"\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z", record["timestamp"]), "timestamp must be ISO 8601"
